# Generated by Django 3.1.1 on 2020-09-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
