# Generated by Django 3.1.1 on 2020-09-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_name',
        ),
    ]
